In [1]:
import numpy as np
import pandas as pd 
df17 = pd.read_csv("daily-shelter-occupancy-2017-csv.csv")
df18 = pd.read_csv("daily-shelter-occupancy-2018-csv.csv")
df19 = pd.read_csv("daily-shelter-occupancy-2019-csv.csv")
df = pd.concat([df17,df18,df19])

In [2]:
df["SHELTER_POSTAL_CODE"].isnull().sum()

5494

In [3]:
#Analysis on missing postal codes:
for n in df.groupby("SHELTER_NAME").groups.keys():
    num_PC = df.groupby("SHELTER_NAME").get_group(n)["SHELTER_POSTAL_CODE"].unique()
    print(num_PC, "--", n)

[nan] -- Birchmount Residence
['M1P 4V8'] -- Birkdale Residence
['M5S 2P1'] -- COSTI Reception Centre
['M6H 3Z5'] -- Christie Ossington Men's Hostel
['M6G 3B1'] -- Christie Refugee Welcome Centre
['M6C 1C2'] -- Cornerstone Place
['M5B 2P3'] -- Covenant House
['M4C 1L7'] -- Dixon Hall - Heyworth House
['M5A 2N2'] -- Dixon Hall - Schoolhouse
[nan 'M3M 2X4'] -- Downsview Dells
['M6K 1Z3'] -- Dufferin Women's Shelter
['M5S 2P9'] -- Eagles Nest Transition House
['M5V 3G9'] -- Eva's Phoenix
['M3B 2T5'] -- Eva's Place
['M2N OE3'] -- Eva's Satellite
['M5B 2A1' 'M4Y 2H6'] -- FV Women's Transition to Housing
['M1E 2M6'] -- Family Residence
['M4X 1K9'] -- Fife House Transitional Program
[nan 'M5V 3W3'] -- Fort York Residence
['M5C 1M3'] -- Fred Victor Women's Hostel
['M6A 2W9'] -- Fred Victor, BUS
['M5A 1T3'] -- Good Shepherd Centre
['M1K 2B5'] -- HFS - Kennedy Shelter
['M6H 1P2'] -- HFS - Savard's Womens' Shelter
['M1K 1M2'] -- HFS - Scarborough Shelter
['M5V 1G8'] -- HFS - Strachan House
['M6E 

In [4]:
df_ynca = df.groupby("SHELTER_NAME").get_group("YMCA House")[["SHELTER_ADDRESS","SHELTER_POSTAL_CODE"]]
df_ynca.groupby("SHELTER_ADDRESS").count()

SHELTER_POSTAL_CODE
SHELTER_ADDRESS                       
485 Queen St West                  730
7 Vanauley Street                  367

In [5]:
df_fvWTH = df.groupby("SHELTER_NAME").get_group("FV Women's Transition to Housing")[["SHELTER_ADDRESS","SHELTER_POSTAL_CODE"]]
df_fvWTH.groupby("SHELTER_ADDRESS").count()

SHELTER_POSTAL_CODE
SHELTER_ADDRESS                       
389 Church Street                  730
512 Jarvis St.                    1460

In [6]:
df_ynca.groupby("SHELTER_ADDRESS").get_group("485 Queen St West")["SHELTER_POSTAL_CODE"].unique()

array(['M5V 2A9'], dtype=object)

In [7]:
df_ynca.groupby("SHELTER_ADDRESS").get_group("7 Vanauley Street")["SHELTER_POSTAL_CODE"].unique()

array(['M5T 2V9'], dtype=object)

In [8]:
df_fvWTH.groupby("SHELTER_ADDRESS").get_group("389 Church Street")["SHELTER_POSTAL_CODE"].unique()

array(['M5B 2A1'], dtype=object)

In [9]:
df_fvWTH.groupby("SHELTER_ADDRESS").get_group("512 Jarvis St.")["SHELTER_POSTAL_CODE"].unique()

array(['M4Y 2H6'], dtype=object)

In [10]:
df.groupby("SHELTER_NAME").get_group("Birchmount Residence")["SHELTER_POSTAL_CODE"].unique()

array([nan], dtype=object)

In [11]:
df.groupby("SHELTER_NAME").get_group("Birchmount Residence")["SHELTER_ADDRESS"].unique()

array(['1673 Kingston Road'], dtype=object)

In [12]:
df.groupby("SHELTER_NAME").get_group("Salvation Army - Florence Booth")["SHELTER_POSTAL_CODE"].unique()

array(['M6J1E6'], dtype=object)

In [13]:
df.groupby("SHELTER_NAME").get_group("Salvation Army - Florence Booth")["SHELTER_ADDRESS"].unique()

array(['723 Queen Street West'], dtype=object)

In [14]:
df.groupby("SHELTER_NAME").get_group("Downsview Dells")["SHELTER_POSTAL_CODE"].unique()

array([nan, 'M3M 2X4'], dtype=object)

In [15]:
df.groupby("SHELTER_NAME").get_group("Downsview Dells")["SHELTER_ADDRESS"].unique()

array(['1651 Sheppard Ave West'], dtype=object)

In [16]:
df.groupby("SHELTER_NAME").get_group("Fort York Residence")["SHELTER_POSTAL_CODE"].unique()

array([nan, 'M5V 3W3'], dtype=object)

In [17]:
df.groupby("SHELTER_NAME").get_group("Fort York Residence")["SHELTER_ADDRESS"].unique()

array(['38 Bathrust St'], dtype=object)

In [19]:
df.groupby("SHELTER_NAME").get_group("Birchmount Residence")["SHELTER_POSTAL_CODE"].unique()

array(['M1N 1S6'], dtype=object)

In [20]:
df.groupby("SHELTER_NAME").get_group("Salvation Army - Florence Booth")["SHELTER_POSTAL_CODE"].unique()

array(['M6J 1E6'], dtype=object)

In [21]:
df.groupby("SHELTER_NAME").get_group("Downsview Dells")["SHELTER_POSTAL_CODE"].unique()

array(['M3M 2X4'], dtype=object)

In [22]:
df.groupby("SHELTER_NAME").get_group("Fort York Residence")["SHELTER_POSTAL_CODE"].unique()

array(['M5V 3W3'], dtype=object)

In [23]:
df.groupby("SHELTER_NAME").get_group("S2H Assessment and Referral Ctre")["SHELTER_ADDRESS"].unique()

array(['67 Adelaide Street East', '129 Peter St'], dtype=object)